title: Random numbers
hero_image: images/banner.png
description: How to generate random numbers in MakeCode
version: 1
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Random numbers in MakeCode
